### ISSUE TITLE
Support `default` filter when `strictVariables` is enabled

### ISSUE THREAD

**Issue by JD557** [bkiers/Liqp#104]
Currently `{{x | default: 1}}` will fail if the `strictVariables` setting is enabled. I'm not sure if this is the intended behavior, since the template should work as expected when `x` is undefined.

It might be a PITA to refactor the code to support this, though.

What's your opinion on this?

**Comment by bkiers** [comment]
Hmmm, that's a tricky one. 

Both this Ruby snippet:

```ruby
require 'liquid'

source = '{{ x }}'

@template = Liquid::Template.parse(source)

result = @template.render({}, { strict_variables: true })

printf("result: '%s'\n", result)
printf("errors: %s\n", @template.errors)
```

as wel as this one:

```ruby
require 'liquid'

source = '{{ x | default: 1 }}'

@template = Liquid::Template.parse(source)

result = @template.render({}, { strict_variables: true })

printf("result: '%s'\n", result)
printf("errors: %s\n", @template.errors)
```

produce the following output:

```
result: ''
errors: [#<Liquid::UndefinedVariable: Liquid error: undefined variable x>]
```

In other words: Ruby renders the template just fine, and handles the templates identical. Liqp also handles both templates identical, but throws an exception in both cases.

Instead of allowing `'{{ x | default: 1 }}` and rejecting (as Liqp does now) `'{{ x }}` in strict mode, I think I would be in favour of making it identical to Ruby's Liquid: in strict mode just render the template, but populate an error list. However, that would mean changing the return type of `Template.render(...)` which would mean breaking changes.

**Comment by JD557** [comment]
I was expecting `'{{ x | default: 1 }}'` to return `'1'`, but since the reference implementation also returns `''`, I'm OK with closing this issue.
