### ISSUE TITLE
Liquid page on shopify.com has moved

### ISSUE THREAD

**Issue by efenderbosch** [bkiers/Liqp#114]
README.md points to http://wiki.shopify.com/Liquid, but that's 404. Should probably point to https://help.shopify.com/en/themes/liquid now.

**Comment by mbaumbach** [comment]
Perhaps https://shopify.github.io/liquid/ is a better location? That contains the subset of filters compared to what is typically available in a Shopify Liquid theme due to shop, locale, and currency contexts that are available in a Shopify store.

For example, the [money filters](https://help.shopify.com/en/themes/liquid/filters/money-filters) are available in Shopify themes, but not in the open source language and also not in this project at the moment.

**Comment by bkiers** [comment]
Done: https://github.com/bkiers/Liqp/commit/3a89d8ad6c7209200b852edb11a6067713ee42a3

Thanks for the heads up @efenderbosch

**Comment by RobertoPegoraro** [comment]
Any plans to create the filter money? I'm needing this filter

**Comment by msangel** [comment]
@RobertoPegoraro this one: https://avada.io/shopify/devdocs/how-to-use-money-filter.html ?

**Comment by RobertoPegoraro** [comment]
Yeap, I did my implementation, but not sure if it is right, I couldn't find the original Liquid implementation.

My code is:

```
public class Money extends Filter {

    @Override
    public Object apply(Object value, TemplateContext context, Object... params) {

        DecimalFormat formatter = new DecimalFormat("###,###,###.00");

        return formatter.format(value);
    }
}
```
